[package]
name = "cynic"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
hex-literal = "0.4.1"
php-discovery = "0.1.2"
serde = { version = "1.0.164", features = ["derive"] }
serde_derive = "1.0.164"
serde_json = "1.0.96"
sha2 = "0.10.6"
